### ISSUE TITLE
Line Scan Optical Distortion

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#105]
The line scan camera model does not implement optical distortion in computeViewingPixel (which is called by groundToImage). Therefore, when the optical distortion is passed in, we can run imageToGround without issue, but can not invert the process.  Setting optical distortion to [0,0,0] allows g2i to 'function', albeit incorrectly.

As a rider, it does not look like the optical distortion implemented in the code matches the model described in the IK. This is from a cursory look and could be entirely incorrect.

**Comment by jessemapel** [comment]
I'm not sure if this is a bug or an enhancement because it is a known issue it just was never implemented?

**Comment by jessemapel** [comment]
@jlaura The math does line up with the calculations from the CTX IK. It's the only distortion is can do right now, but that's what it has.

**Comment by jessemapel** [comment]
@jlaura Do you have a CTX ISD somewhere that I can test this with?
