### ISSUE TITLE
Standardize ISD Keywords / State

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#12]
The state keywords differ between the models that we have implemented.  These should be standardized as follows:

- [x] Create a wiki page with a table for the framing and line scanner keywords with each keyword on a separate line.
- [ ] Generate an RFC issue with a set of isd / state keywords
- [ ] Once we have consensus, refactor the code for standardize keywords.

**Comment by thareUSGS** [comment]
see old wiki - port over? https://github.com/USGS-Astrogeology/camera_model/wiki

**Comment by kberryUSGS** [comment]
https://github.com/USGS-Astrogeology/CSM-CameraModel/wiki/Standard-ISD-Keywords

**Comment by thareUSGS** [comment]
Need to test HRSC ISD output. Also need to update code (just a reminder).

**Comment by jessemapel** [comment]
Update the wiki page to point to the swagger spec from pfeffernuesse
