### ISSUE TITLE
Generate Line Scan tests

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#120]
Similar to how we tested the framing camera, we need generic line scan tests.

**Comment by jessemapel** [comment]
Current testing plan:

- A linear flyby with a fixed viewing angle
- A fixed position with a constant camera rotation velocity

I'm going to try and generate some test numbers for this.

**Comment by jessemapel** [comment]
[csm_ls_test.pdf](https://github.com/USGS-Astrogeology/CSM-CameraModel/files/2443342/csm_ls_test.pdf)

Here's the LS test case math. I feel good about all of it, except maybe the final rotational velocity for the second case. I think that's how rotational velocity works?

**Comment by jlaura** [comment]
Linescan tests:

- [ ] i2g / g2i 
- [ ] off body
- [ ] A linear flyby with a fixed viewing angle
- [ ] A fixed position with a constant camera rotation velocity
- [ ] State test / resetting the state - dump state;reset;fail
- [ ] Test distortion (tests #105)
- [ ] Tests for #165
- [ ] Tests for #166
- [ ] Test imageToRemoteImagingLocus
- [ ] Test imageToProximateImagingLocus
- [ ]

**Comment by jessemapel** [comment]
Example math for the [constant velocity](https://raw.githubusercontent.com/wiki/USGS-Astrogeology/usgscsm/documents/LS_Image_To_Ground_Example.pdf) and [constant angular velocity](https://raw.githubusercontent.com/wiki/USGS-Astrogeology/usgscsm/documents/pan_ls_math.pdf)
