### ISSUE TITLE
#define necessary in cpp

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#136]
Are the `#define` lines at the top of the cpp necessary for windows?

**Comment by jessemapel** [comment]
What documentation do you have that says we need them?

**Comment by jlaura** [comment]
As far as I can tell, the answer here is no. [These docs](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-define-directive-c-cpp?view=vs-2017) suggest that these are for setting up macros. I only see the `#define` in the LS, the library name is defined twice (...), and it does not appear to be being used. PR open to pull these out.
