### ISSUE TITLE
Make the Framer CSM compliant

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#164]
In GXP, the framer is currently not instantiating. @thareUSGS would like to be able to instantiate a framer. We need to confirm that all necessary methods are implemented.

**Comment by jlaura** [comment]
See #74 for a lead.

**Comment by jlaura** [comment]
I edited the title so that this is not a pseudo duplicate of #142. Here is a listing of the methods that have been modified with dummy returns to fix #142.

- [ ] 222 - imageToGround
- [ ] 533 - getUnmodeledCrossCovariance
- [ ] 564 - getPedigree
- [ ] 596 - getTrajectoryIdentifier - the 'dummy' in here might be acceptable
- [ ] 610 - getReferenceDateAndTime - also might be acceptable
- [ ] 1020 - hasSharableParameters - also might be acceptable
- [ ] 1029 - getParameterSharingCriteria - this should be raising the correct error now
- [ ] 1077 - getGeometricCorrectionName - also should be raising the correct error
- [ ] 1097 - getGeometricCorrectionSwitch - as above
- [ ] 1066 - getCrossCovarianceMatrix - this is a dummy implementation, but should be acceptable to GXP

**Comment by Kelvinrr** [comment]
Looks like the only ones that actually need to be implemented beyond what's already in #151 is `imageToGround` and `getPedigree`.  Although `getPedegree` is dubious. The rest is not really necessary to get this going for now.
