### ISSUE TITLE
Share ISD parsing code between LS and Framer

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#176]
This is largely prompted by #163. The framer has significantly more robust ISD parsing, but we know the linescan instantiates properly in GXP.

Both use the exact same ISD format, so can we share that code between them?

**Comment by thareUSGS** [comment]
While I am hesitant to change this before we fix GXP support, I think we should do it. Especially if we can manage the update in the current sprint.
