### ISSUE TITLE
Add some kind of desired precision test

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/usgscsm#182]
See: https://github.com/USGS-Astrogeology/usgscsm/pull/180

**Comment by jessemapel** [comment]
This is already handled

https://github.com/USGS-Astrogeology/usgscsm/blob/dev/src/UsgsAstroLsSensorModel.cpp#L607

**Comment by jessemapel** [comment]
@kberryUSGS Is this for our tests or is this something that needs to be tested in the actual code and then a warning/exception needs to be thrown?

**Comment by kberryUSGS** [comment]
@jessemapel :+1: Never mind then, didn't realize this had already been tested.
