### ISSUE TITLE
Small documentation/cleanup tasks

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/usgscsm#191]
- [ ]  Add documentation for some of the Utilities functions that are missing it.
- [ ]  Remove unneeded comments from top of linescan test file that are talking about problems that no longer exist ("commented out tests...")

**Comment by jessemapel** [comment]
Do the get_ methods need to be documented? Most of them are so simple.

**Comment by kberryUSGS** [comment]
I think it's fine to leave the get_ methods undocumented.
