### ISSUE TITLE
1.1.0 Release Has GTest Dependency?

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#193]
Working on the conda-forge build and getting test errors. It looks like gtest.h was added to the framer header.

https://github.com/USGS-Astrogeology/usgscsm/blob/dev/include/usgscsm/UsgsAstroFrameSensorModel.h#L8

This looks like it was done in error?

**Comment by kberryUSGS** [comment]
I can take a look at this.

**Comment by jlaura** [comment]
Here is the git blame line. I bet this is an error and got in with PR for distortion.

`6a1c1e16 include/usgscsm/UsgsAstroFrameSensorModel.h      (Tyler Wilson     2018-08-24 09:45:16 -0700   8) #include <gtest/gtest.h>`

**Comment by kberryUSGS** [comment]
@jlaura It doesn't build with the gtest include taken out. 

All of the friend tests in here cause compilation errors like: 

```
In file included from /home/kberry/csm/CSM-CameraModel/src/UsgsAstroPlugin.cpp:3:
/home/kberry/csm/CSM-CameraModel/include/usgscsm/UsgsAstroFrameSensorModel.h:317:17: error: ‘FramerParameterizedTest’ has not been declared
     FRIEND_TEST(FramerParameterizedTest,JacobianTest);
```

If the gtest include is taken out.

**Comment by jlaura** [comment]
weird - I'll add a gtest dependency to the build.

**Comment by jlaura** [comment]
I am going to reopen this. I am not sure how the conda build was successful before, given that the gtest dependency has been in here, but I can not do a conda build with how we are including test currently. 

I think that we need to add:
```
# Find GTest
find_package(GTest REQUIRED)`
```

To the CMakeLists.txt and then modify the includes as:
```
target_include_directories(usgscsm
                           PUBLIC
                           ${USGSCSM_INCLUDE_DIRS}
                           ${CSM_INCLUDE_DIR}
                           ${GTEST_INCLUDE_DIRS}
)
```

I think though that this will mess with the way that gtest is being included as a submodule. It looks like the submodule is the reason that we have been able to include GTest without actually including it. Using the above method, we would use gtest from conda-forge.

With how we are including gtest right now, I am not sure how conda build has been working at all. Thoughts?

**Comment by kberryUSGS** [comment]
@jlaura I am not sure if this will fix it because I didn't try to do a conda build, but I just put up PR #194 which will build and run tests without error without the gtest submodule present.

**Comment by jessemapel** [comment]
If this is based on friend tests, we can just remove those and make functions public. That's how we test the rest of it.

**Comment by kberryUSGS** [comment]
@jessemapel That sounds good to me. I'm not sure why the PR I put up is failing on appveyor and travis (linux is failing with a specific test failure, and OSX looks like it had some kind of linking failure.

**Comment by jlaura** [comment]
@jessemapel @kberryUSGS Any objection to me peeling of a 1.1.1 release with the changes to gtest?

**Comment by jessemapel** [comment]
@jlaura This fix needs to be ported to master first. Then, a release can be pulled off master.

**Comment by jlaura** [comment]
dev -> master still has merge issues?

**Comment by jlaura** [comment]
I'll move over to gitter so we don't muddy this issue.
