### ISSUE TITLE
Non deterministic behavior on `imageToGround`

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/usgscsm#205]
Whenever I run `imageToGround` using CTX images (I assume this may be a problem with the LS camera model and therefore affects all LS images) subsequent calls return different values on occasion. Sometimes returns a number and later nans on the same camera instance.  

![csmerror](https://user-images.githubusercontent.com/13245976/54707250-e58e4b80-4afd-11e9-8e25-6622076de139.gif)

This is simply running the footprint generation code from autocnet server but the pain point seems to be `imageToGround`. Times when shapely errors out are times when `imageToGround` produces nans.

**Comment by Kelvinrr** [comment]
This was caused with the number of ephemerides set to 3 and quats set to ~1000 (numbers coming from ISIS spice inited cubes originally, I moved to using spice kernels and manually set the numbers of ephems and quats and this was the result). Changing both to closer match the number of lines and samples (a couple thousand per image) it no longer has the issue. No idea why.

**Comment by jessemapel** [comment]
@Kelvinrr Is this after #202

**Comment by Kelvinrr** [comment]
yeah clean build from dev

**Comment by jessemapel** [comment]
@kelvinrr Can you post a gist of the notebook you were running and/or provide the ISD/state for the LS that you found this with?

**Comment by jessemapel** [comment]
This appears to be caused by the langrange interpolation not checking that it actually has enough data to interpolate over and is ready garbage off either end of the array.

**Comment by thareUSGS** [comment]
In the past we have always had to add (extrapolate) 10 ephemerides to the begin and end of the ISD. Would that help here?  for more see: https://github.com/USGS-Astrogeology/ISIS3/blob/e53a8c26e57c79cc3ab373edc2f5eeacf6f15663/isis/src/socet/apps/socetlinescankeywords/main.cpp#L437

**Comment by jessemapel** [comment]
@thareUSGS I think we just have to have a minimum of ~6 points. Regardless, the lagrange interpolation code should handle this stuff more gracefully. Lagrange interpolation should work with as few as 2 points.
