### ISSUE TITLE
ISD Loading is Very Janky - Filename Issues

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#206]
Out method for expecting a side car file containing the ISD with a name built as <strip anything after the last '.'> + json is very janky. What if I want to push in a string label bypass the file read completely?

**Comment by jessemapel** [comment]
We can support other types of loading, but it's going to be hard to get away from something filename based because how ISDs are used with the CSM API. If we have some sort of special routine to insert a label into the ISD, most SETs won't actually use it.

Our current scheme is built around the idea that SETs simply try all of the different constructors for ISD and its subclasses.

**Comment by Kelvinrr** [comment]
What is stopping use from simply constructing the ISD object out of the JSON string and simply checking for JSON string vs filename in the construct from ISD function?

**Comment by jessemapel** [comment]
@Kelvinrr A generic SET won't know how to find the JSON file and load it into an ISD

**Comment by Kelvinrr** [comment]
Basically what I was implying, support both. JSON for our tools and file paths for a generic SET.

**Comment by scsides** [comment]
In my initial reading of the CSM/ISD specs, I thought there was something about a stream or string spec.

**Comment by jlaura** [comment]
I just wrapped the [BytestreamISD class](https://github.com/USGS-Astrogeology/swigcsm/pull/19). It looks like usgscsm would then need to be updated to make us of this class. Right now, we assume as ISD with only a filename: https://github.com/USGS-Astrogeology/usgscsm/blob/dev/src/UsgsAstroPlugin.cpp#L144

Is this an instance where an overloaded function would be appropriate? If so, I'll close this issue and open a new one describing the solution (or just do a PR).

**Comment by jessemapel** [comment]
@jlaura By the CSM API we cannot overload the plugin create from ISD method. We'd have to just modify that code to try and cast to a BytestreamISD.

**Comment by jlaura** [comment]
So the parameter comes in typed as an ISD (the parent) and we/the compiler have no way in introspect (except via a cast) to check if it is a BytestreamISD?

**Comment by jessemapel** [comment]
As far as I can tell yes. C++ doesn't support Python like introspection and the ISD class structure doesn't seem to have any sort of a "what type of ISD am I" method.

**Comment by scsides** [comment]
If there are any virtual functions in the base (ISD) we could consider using RTTI.

**Comment by jessemapel** [comment]
I'm going to close this issue because I still don't see a good way around this for the ISD. For now if you want to do something without having to have a sidecar file then you should use the State construction API instead of the ISD construction API.
