### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#210]
We should have an option in the ISD to log stuff. The spdlog library seems good for this. See #185 for a bad implementation of this.

**Comment by jessemapel** [comment]
How much should we log? Should it be a sort of stack trace?

**Comment by jessemapel** [comment]
Created a branch called logging with spdlog setup and the basics of an optional logger in the framer.

**Comment by jlaura** [comment]
Why don't we start with some minimal logging and then build from there as needed? Do we need to extend the ISD specification? If so, I can take care of that.

**Comment by jessemapel** [comment]
@jlaura This adds a new optional keyword called `m_logFile` that is the path to where the log file will be written.
