### ISSUE TITLE
The line_scan_rate uses ISIS lines

### ISSUE THREAD

**Issue by SgStapleton** [USGS-Astrogeology/usgscsm#239]
Should be using CSM start line value (0), but is using ISIS start line value (0.5)

**Comment by SgStapleton** [comment]
https://github.com/USGS-Astrogeology/ale/issues/208

**Comment by jessemapel** [comment]
At this point we're not changing the ISD so we won't be fixing this until we have significant changes to make. Internally we could fix this on ISD->state, but it's not a priority.
