### ISSUE TITLE
Add getIlluminationDirection to the LS sensor model

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#251]
This is part of the CSM API that we don't support right now but could. It returns the vector to the sun at a ground point on the surface. This is an easy calculation.

**Comment by jessemapel** [comment]
From the CSM spec:

5.12.34csmSensorModel::getIlluminationDirection()

SYNOPSIS

virtual CSMWarning* getIlluminationDirection(const double& x, const double& y, const double& z, double& direction_x, double& direction_y, double& direction_z) const throw (CSMError) = 0;

DESCRIPTION

The getIlluminationDirection() function calculates the direction of illumination at the given ground position x, y, z. The ground position is given in the coordinate system described in paragraph 5.1.2. The direction vectors are returned in the same coordinate system.

INPUTS

x, y, and z are ground coordinates in meters.

OUTPUTS

CSMWarning is a pointer to a CSM warning object. A value of NULL indicates no warning is present.

Upon successful completion, getIlluminationDirection() produces three doubles, direction_x , direction_y  and direction_z,defining a direction vector that points from the illumination source to the given ground point.

CSMError returns the CSM Error object. A thrown CSMError is a terminal condition and must be caught by the SET program.

**Comment by jessemapel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement getIlluminationDirection on the LS](https://trello.com/c/0o5xZN3e/5-implement-getilluminationdirection-on-the-ls)

**Comment by AustinSanders** [comment]
Closed in #259

**Comment by AustinSanders** [comment]
Closed in #259
