### ISSUE TITLE
New ground to image needs to determine if +lines on the detector is +lines in the image

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#267]
For some images, we're seeing that +lines on the detector is -lines in the image, this causes groundtoimage to fail quite spectacularly. This can be accomplished with a simple check at initialization.

**Comment by thareUSGS** [comment]
If we move temporarily from working on CSM, do we know a quick list of which instruments ate impacted?

**Comment by jessemapel** [comment]
I need this fixed for control network metrics. So, I'm fixing it right now. It's a small fix.
