### ISSUE TITLE
UsgsAstroLsSensorModel has getParameterValue() when csm already has getParameter()

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/usgscsm#269]
csm creates a Parameter object which contains a parameter's name, value, unit, and type. Why do we need a function that does just part of a function provided by the csm api?

**Comment by jessemapel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get parameter issue](https://trello.com/c/aZCM2oSS/35-get-parameter-issue)

**Comment by jessemapel** [comment]
The CSM getParameter function calls getParameterValue. So we need to keep ours.
