### ISSUE TITLE
Add logging levels to usgscsm

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/usgscsm#301]
The extra logging is useful, but the file sizes on the logs get excessive pretty quickly (ex ~0.5 gig) for a very small number of actions in GXP.

**Comment by jessemapel** [comment]
I think a better option is to implement logging levels. https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/common.h#L139 We could enable different levels of logging, or log different things to different files.
