### ISSUE TITLE
Update SAR to work with "ale" isd format

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/usgscsm#303]
Right now, the SAR sensor model only works with "usgscsm"-formatted isds. It needs to be updated to work with "ale" (the unified format) isds.

**Comment by oleg-alexandrov** [comment]
Will this amount to just some reformatting and such, or will this need some deep-down "spice-mining"? I can likely take a stab at it this week, if there's some advice at what this would entail.

**Comment by jessemapel** [comment]
I've already got a draft of this from a long time ago in #310. Most of the work is just changing how the ISD gets converted into the model state. The new unified formatter writes out the sensor state, relative to the sun barycenter in J2000, and then writes out the target state, in the same way, and the target rotation. So, the ISD->state function has to convert those into sensor state relative to the target center in the target frame. There's already logic for this in the line scanner we can likely re-use.

**Comment by jessemapel** [comment]
The SAR test ISDs will also need to be updated to the new ISD format which could be annoying.

**Comment by oleg-alexandrov** [comment]
Looks like doable if detailed work. I'll give it a try some time this week. 

Will the old model not be supported going forward?

**Comment by jessemapel** [comment]
Model states will still be supported, but old ISDs will not be.

**Comment by oleg-alexandrov** [comment]
Fixed in https://github.com/USGS-Astrogeology/usgscsm/pull/389. I think this can be closed.
