### ISSUE TITLE
Remove computeAllSensorPartials from Frame and Ls sensor model or modify to call parent after logging

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/usgscsm#305]
It's not needed, as this is implemented in RasterGM. The Ls sensor model's function does add logging, but if we want to keep the logging, we can leave this method in the Ls sensor model, and have its entire contents be (1) logging (2) call the parent's (RasterGM's) version of this function.

**Comment by jlaura** [comment]
Is this closable? Looks like the auto close in #311 just might not have worked?

**Comment by kberryUSGS** [comment]
Yes, thanks! Closed by #311
