### ISSUE TITLE
HiRISE pairs acting very odd (GXP)

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/usgscsm#334]
@jessemapel Now that I have been able to test these two HiRISE samples in GXP 4.3, I can confirm some strange behavior undoubtable the same as @oleg-alexandrov was seeing.
https://github.com/USGS-Astrogeology/usgscsm/wiki/CSM-Stereo-Testing-Examples

Triolet actually loads into GXP with very reasonable footprints (location is not great but in the right area) and the aspect (width versus width) looks good also. When viewing in stereo, the initial load looks reasonable although larger parallax than normal. But upon moving a little in stereo, one image collapses in Y by about half. So the first image remains the correct aspect and the second smashes in half (in the Y direction) only. Very strange. There is no way to recover from that in trying to force control. 

Jezero also has okay good initial location and footprint overlap looks good. Stereo looks good too (no smashing). Automatic point measure (APM) fails pretty harshly but I can force some manual control and triangulation. Running a DEM now and will check back in the morning. APM "should" work pretty well for this, but maybe the initial locations are just too far off. 

I guess I recommend perhaps testing both Triolet images in a knoten notebook (to see if the returned footprint acts up). I'll be happy to demo in GXP too.

**Comment by jessemapel** [comment]
Okay, it turns out we were getting bit by the old lagrange interpolation. The ISIS/ALE interpolation methods are much more robust and we ended up getting the time spacing wrong when we ingested data from ISIS cubes. I've put in a PR to just re-interpolate, but the proper solution is likely to just use the more robust stuff and throw out the old lagrange interpolation as it's still not great on the top and bottom of the images.

@thareUSGS Can you try testing with the CI artifacts here: https://ci.appveyor.com/project/jlaura/usgscsm/builds/38564271/artifacts

**Comment by thareUSGS** [comment]
On it - I will try it in the morning. Good timing as our licenses kicked back in today.

**Comment by thareUSGS** [comment]
@jessemapel and @oleg-alexandrov Initial automatic point measurement in GXP is working so much better with update (existing Triolet stereo example). I haven't actually gone through the whole process though. With no edits, triangulation = RMS 1.5 pixels (not bad).

**Comment by oleg-alexandrov** [comment]
Glad to hear that. It will take me some more time to loop around the CSM work. 

Looking forward to updates for the other datasets as well, particularly for LROC. Our shape-from-shading tool (it is used for creating maps for the future VIPER moon rover) would benefit nicely from a speedup at the bundle adjustment stage from using the CSM model with multiple threads.
