### ISSUE TITLE
Format of .json file

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/usgscsm#337]
I am curious as to why the USGSCSM .json file is stored in one line. Sure it can be parsed either way, but when comparing two such files it becomes a challenge, as that one line can have 400 k characters on it.

**Comment by jessemapel** [comment]
White space is not specified by JSON. So, you can have spaces and new lines in your JSON files as long as they aren't parts of string values. So, the following are equal:

```
{some_key : some_value}
```

and

```
{
  some_key : some_value
}
```

For example, our test ISDs have newlines and indents:

https://github.com/USGS-Astrogeology/usgscsm/blob/dev/tests/data/constVelocityLineScan.json

If you're using ALE to generate your ISDs, you can write them to the file with each key on a new line and nested indenting by using pretty printing from the Python JSON module. See the Python [JSON docs](https://docs.python.org/3/library/json.html) for more pretty printing options.

Here's an example:

```
import ale, json
one_line_isd_string = ale.loads(label)
# Convert back to a dict
isd_dict = json.loads(one_line_isd_string)
multi_line_isd_string = json.dumps(isd_dict, indent=2)
```

Note, that you can also use ale.load to just get a dictionary from the start but you need to give the JSON module a special encoder to handle the numpy arrays.

```
import ale, json
isd_dict = ale.load(label cls=ale.drivers.AleJsonEncoder)
multi_line_isd_string = json.dumps(isd_dict, indent=2)
```

**Comment by oleg-alexandrov** [comment]
Jesse, thank you. This is helpful. Maybe it would be beneficial if the default way of saving .json uses multiple lines. Sure not many people peek inside of .json files, but if we get to the point where this is a format rivals .cub, which we hope so,  .json files being short, not having binary blobs, and independent of multi-GB kernel databases may benefit from the file being easier to read. Other files I usually encounter, such as Digital Globe and various XML-based formats, are obviously not as pretty as .json but being on multiple lines one can at least peek at them. I can of course make a json file multi-line with a perl one liner but thinking more of other folks.

**Comment by jessemapel** [comment]
We could always modify `ale.loads` to add a json.dumps kwargs variable and then default it to `{indent:2, sort_keys=True}`. That would make it default to this style of output and then allow users to override that if they want.

**Comment by oleg-alexandrov** [comment]
That can work.

**Comment by oleg-alexandrov** [comment]
I made a pull request at https://github.com/USGS-Astrogeology/ale/pull/421.
