### ISSUE TITLE
CSM to ISIS comparison has issues with LRO

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/usgscsm#338]
I found that the CSM model can fit well some LRO models and not well others. CSM seems to work well with the HiRISE and CTX data. I did this evaluation both using knoten, my own ASP ground-to-image test, and creating DEMs with CSM and ISIS and comparing them. All three modalities agree when a fit is good or not.

As a sanity check, I first verified the dataset M1142142198RE, which is evaluated at https://github.com/USGS-Astrogeology/knoten/blob/master/examples/lrocnac_isis_cmp.ipynb. (I made some adjustments to the procedure to reflect the changed API, as seen further down.)

This dataset does very well on all metrics. 

Then, from the testing examples at https://github.com/USGS-Astrogeology/usgscsm/wiki/CSM-Stereo-Testing-Examples I evaluated M1127782730LE.lev1.8bit, M1121188383LE.lev1.8bit, and M1167355858LE.lev1.8bit (a left image in each of those testcases). The fit is not good for the first two, and very good for the last. 

I also evaluated, for completeness,  the two HiRISE examples, and the CTX example, so ESP_037330_1990_REDmos_hijitreged.balance.noproj.8bit, ESP_011969_1425_REDmos_hijitreged.balance.noproj.8bit, and B17_016219_1978_XN_17N282W.8bit. 

These do very well on the isis2csm_data metric from knoten, but don't do well on the csm2isis_data metric. 

I also created ASP DEMs with CSM and ISIS cameras and compared them. I get not good results (DEM differ in position) for the first two LRO testing examples, very good ones for the third, and very good ones for HiRISE and CTX. Which precisely agree with results obtained via the isis2csm_data metric in vis.py. Need to think more of the csm2isis_data metric for these.

Here is the approach I used. ISIS 4.4.0 was used to do 

<pre>
spiceinit from = CubFile.cub shape = ellipsoid
</pre>

for the LRO data. The spiceinit is needed since the cub files the CSM-Stereo-Testing-Examples page did not have the ShapeModel in the right location.  I did not do spiceinit for the HiRISE and CTX data as things worked for those. 

Then I used usgscsm 1.5.2 to create the CSM files as this:

<pre>
usgscsm_str = ale.loads(cub_loc)

csm_isd = os.path.splitext(cub_loc)[0] + '.json'
with open(csm_isd, 'w') as isd_file:
    isd_file.write(usgscsm_str)
</pre>

The vis.py tool from knoten was used for evaluation. 

Attached are the reports from vis.py, in the same order as described above. First the "sanity check" dataset  M1142142198RE, then the three LRO NAC datasets, the two HiRISE datasets, and the CTX dataset. 

[report_M1142142198RE.txt](https://github.com/USGS-Astrogeology/usgscsm/files/6742989/report_M1142142198RE.txt)
(good)

[report_M1127782730LE.lev1.8bit.txt](https://github.com/USGS-Astrogeology/usgscsm/files/6743060/report_M1127782730LE.lev1.8bit.txt)
(bad)

[report_M1121188383LE.lev1.8bit.txt](https://github.com/USGS-Astrogeology/usgscsm/files/6743007/report_M1121188383LE.lev1.8bit.txt)
(bad)

[report_M1167355858LE.lev1.8bit.txt](https://github.com/USGS-Astrogeology/usgscsm/files/6743011/report_M1167355858LE.lev1.8bit.txt)
(good)

[report_ESP_037330_1990_REDmos_hijitreged.balance.noproj.8bit.txt](https://github.com/USGS-Astrogeology/usgscsm/files/6743019/report_ESP_037330_1990_REDmos_hijitreged.balance.noproj.8bit.txt)
(good for the isis2csm_data  metric)

[report_ESP_011969_1425_REDmos_hijitreged.balance.noproj.8bit.txt](https://github.com/USGS-Astrogeology/usgscsm/files/6743025/report_ESP_011969_1425_REDmos_hijitreged.balance.noproj.8bit.txt)
(good for the isis2csm_data  metric)

[report_B17_016219_1978_XN_17N282W.8bit.txt](https://github.com/USGS-Astrogeology/usgscsm/files/6743026/report_B17_016219_1978_XN_17N282W.8bit.txt)
(good for the isis2csm_data  metric)

Any thoughts?

**Comment by jessemapel** [comment]
This is good to know. I'll need to dig into these issues and see why some of our LROC images are so bad. @thareUSGS this corroborates what LRO and BAE have been talking about in those e-mails.

I'm going to be out for the next week, but I want to start looking into these at least a little bit once I get back.

**Comment by oleg-alexandrov** [comment]
I think I found the issue with this. I propose a fix at https://github.com/USGS-Astrogeology/usgscsm/pull/341, which was extensively tested and it works, but which may need more tuning to improve its performance.

**Comment by oleg-alexandrov** [comment]
This was fixed and tested by the above pull request.
