### ISSUE TITLE
How to apply a rotation and translation to a linescan camera

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/usgscsm#339]
I wonder if there is any simple API to take a linescan camera in json format and apply to it a rotation and translation adjustment. I've been looking over the usgscsm and ale code and there seems to be a handful of transforms, such as time-dependent rotations, constant rotations, and body to camera rotations, then also the positions and velocities, all of which of course need to be applied in some predetermined order and direction. 

To give more context, I need this for bundle adjustment. So, once one has a little rotation R and translation T to apply to a camera, I'd need to know how to propagate these into the CSM model. Thanks.

**Comment by jessemapel** [comment]
As far as I'm aware, there is no way to do this with the CSM API. Because it has to support things like replacement sensor models, the CSM API doesn't surface adjustments in a "geometric" sense. Instead all adjustments are via generic parameters that each implementation defines internally. For our LS, we define position and rotation biases in terms of down-track, cross-track, altitude, but that's just our model. Other models can define their terms however they want. For example, we have a [simple testing model](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/tests/TestCsmModel.cpp) in ISIS that only has 3 parameters:

* central longitude
* central latitude
* scale in PPD

For bundle adjusting CSM in ISIS, we abstracted our observation interface to operate at the level of generic parameters.

**Comment by oleg-alexandrov** [comment]
Indeed, there is no hope the CSM abstraction would know about all the implementation details for a specific camera, like linescan. 

So, I guess, one has to manipulate the json object directly, which is fine by me, or peeking deep into ALE. (I looked at its Orientations logic but does not seem to have what I need.)

I must say there's a lot of things in ALE. In addition to what I mention before, there's more than one constant frame, and potentially more than one time-dependent frame. It is not clear if the rotations act from camera to ground, or in reverse, or the order they are applied, and around what point the rotation is applied (I figured experimentally it is not the planet center). 

I looked a bit at the csm param set variables, which are used in the isis bundle adjustment, but could not get to the bottom of it. 

So maybe I can put it this way. If I load the json in numpy and pull out of it the instrument orientation and positions as arrays of float values, and I want to apply a transform whose effect would be the camera rotating around the planet center by 1 degree longitudinally (hypothetically speaking), what is the magic thing I should be doing to those orientation and positions arrays?

Should I be concerned at all with the body to camera transform? 

Should I multiply first the rotations in the .json by the inverse constant rotation, then multiply by my rotation (or its inverse), then multiply back by the constant rotation? 

If I want the camera to shift, should I just add a vector to all those position vectors? 

Should I handle all constant frames if there is more than one?

**Comment by jessemapel** [comment]
I would recommend against working around the CSM API as we make no guarantee that our state JSON format remains exactly the same from version to version. The ISD JSON format is more stable but there are still things I'd like to see change such as storing the entire frame rotation tree.

Which JSON are you looking to work with?

**Comment by oleg-alexandrov** [comment]
The ISD JSON could work just as well as anything. 

I guess I could figure out the details on my own, and work with Ale and not JSON, as well. Whichever way makes more sense.

I am trying to make some educated guesses, which I hope you can confirm, since the number of combinations in which things may work could be large. 

My best guess is that I can ignore the body parameters at all, and also anything about the number of frames, and focus on instrument_pointing.  I guess if I have to shift the cameras I need to add values to ephemeris positions.  If the camera must be rotated, with each rotation around the ephemeris position, I guess I can just multiply the constant rotation to the left by the rotation matrix. Would this work?

**Comment by oleg-alexandrov** [comment]
I've been reading through the code. There seem to be two orientation objects, one from sensor to body, second from body to world, each with its own constant rotation and time-dependent rotation, and all four of these are multiplied and interpolated as need arises. Then there's the sensor positions too. 

Now, the reason I am looking at this because of the deliverable of being able to export the JSON state of a CSM model after an adjustment comprising of  a rotation and translation (in world coordinates) is applied to it, which is what our bundle adjustment does. 

It appears that the JSON state is determined as result of doing all those multiplications and interpolations mentioned before, so I don't need to go that deep into the model and have to just apply my rotation and translation to the positions and quaternions in the JSON state. 

Now, you are saying that this state is not stable, which is not very encouraging. But hey, that's what I was tasked to do, computing this state, and that I will do. 

If I manage to make it work, and at this stage things look clear enough, the logic of applying a rotation + translation to a JSON state may belong in the linescan sensor class of the usgscsm package maybe, which means not using the csm abstraction layer, which will be some extra maintenance pain I guess.

I looked more at csm::Param::set as implemented in the linescan sensor class and it looks that it is not helpful for modifying the state, it only does some covariance business. It is still not clear to me you folks managed to do bundle adjustment without modifying a state the way I hope to have it modified.

**Comment by jessemapel** [comment]
Here's what's in the ISD for position and rotation:

body_rotation holds the rotation from J2000 to the target frame
instrument_pointing holds the rotation from J2000 to the sensor frame
sun_position holds the position of the sun relative to the body in the J2000 frame
instrument_position holds the position of the sensor relative to the body in the J2000 frame

If you want to apply a constant rotation all you need to do is right multiply the constant_rotation matrix in the instrument_pointing object by your new rotation's matrix. For a time dependent rotation, it's much more complex as you need to combine the constant rotation into the time dependent rotations and then apply your time dependent rotation. In order to do this, you'll need to re-interpolate one or both of the time dependent rotations.

You can do this in ALE here are some code snippets:

Constant rotation
```
// Read ISD
json jsonIsd = json::parse(imageSupportData);
ale::Orientations instrumentPointing = ale::getInstrumentPointing(jsonIsd);

// Apply rotation
ale::Rotation updateRot({0, 1, 0}, M_PI); // 180 degree rotation about +Y
ale::Orientations updatedInstrumentPointing = instrumentPointing * updateRot;

// Update ISD
ale::Rotation newConstRot = updatedInstrumentPointing.getConstantRotation();
jsonIsd["instrument_pointing"]["constant_rotation"] = newConstRot.toRotationMatrix();
```

Time-dependent rotation
```
// Read ISD
json jsonIsd = json::parse(imageSupportData);
ale::Orientations instrumentPointing = ale::getInstrumentPointing(jsonIsd);

// Apply rotation
// 0, 90, and 180 degree rotations around +Y
std::vector<ale::Rotations> rotVec = {
    ale::Rotation({0, 1, 0}, 0),
    ale::Rotation({0, 1, 0}, M_PI/2.0),
    ale::Rotation({0, 1, 0}, M_PI)};
std::vector<double> timeVec = {0.0, 1.0, 2.0};
ale::Orientations updatePointing(rotVec, timeVec);
ale::Orientations updatedInstrumentPointing = instrumentPointing * updatePointing;

// Update ISD
ale::Rotation newConstRot = updatedInstrumentPointing.getConstantRotation();
jsonIsd["instrument_pointing"]["constant_rotation"] = newConstRot.toRotationMatrix();

std::vector<ale::Rotation> newRotations = updatedInstrumentPointing.getRotations();
std::vector<ale::Vec3d>  newAvs = updatedInstrumentPointing.getAngularVelocities();
std::vector<double> newTimes = updatedInstrumentPointing.getTimes();

jsonIsd["instrument_pointing"]["quaternions"] = basic_json::array();
jsonIsd["instrument_pointing"]["angular_velocities"] = basic_json::array();
jsonIsd["instrument_pointing"]["ephemeris_times"] = basic_json::array();

for (size_t i = 0; i < newTimes.size(); i++) {
    jsonIsd["instrument_pointing"]["quaternions"].push_back(newRotations[i].toQuaternion());
    ale::Vec3d avVec = newAvs[i];
    jsonIsd["instrument_pointing"]["angular_velocities"].push_back({avVec.x, avVec.y, avVec.z});
    jsonIsd["instrument_pointing"]["ephemeris_times"].push_back(newTimes[i]);
}
```

If you want to apply a constant translation you need to rotate the translation into the J2000 frame at each time and then add that into the instrument_position. For time dependent translations you have the same re-interpolation needs as the rotations.

ALE doesn't have as nice of a position addition interface so you have to do it more manually:

Constant translation
```
// Read ISD
json jsonIsd = json::parse(imageSupportData);
ale::Orientations j2000ToTarget = ale::getBodyRotation(jsonIsd);
ale::States instrumentPosition = ale::getInstrumentPosition(jsonIsd);

// Update instrument positions
std::vector<double> translation = {1.0, 2.0, 3.0};
std::vector<double> times = instrumentPosition.getTimes();
std::vector<ale::Vec3d> positions = instrumentPosition.getPositions();
std::vector<ale::Vec3d> updatedPositions;
for (size_t i = 0; i < times.size(); i++) {
    ale::Vec3d rotatedTranslation = j2000ToTarget.rotateVectorAt(times[i], translation, ale::SLERP, true);
    updatedPositions.push_back(positions[i] + rotatedTranslation);
}

// Update ISD
jsonIsd["instrument_position"]["positions"] = basic_json::array();
for (auto position : updatedPositions) {
    jsonIsd["instrument_position"]["positions"].push_back({position.x, position.y, position.z});
}
```

**Comment by jessemapel** [comment]
We also finally have our ALE C++ API docs building:

https://ale.readthedocs.io/en/latest/library/capi/

**Comment by oleg-alexandrov** [comment]
Thank you, this is very helpful. 

Here's a potential pull request which can add this functionality to the linescan camera. (For when you are back from vacation.) https://github.com/USGS-Astrogeology/usgscsm/pull/340

**Comment by oleg-alexandrov** [comment]
Resolved by the pull request.
