### ISSUE TITLE
Have the json state be saved on multiple lines

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/usgscsm#344]
ALE now saves an ISD on multiple lines, but USGSCSM saves the model state as one line. I would think that, as before, it would help with readability if the state was saved on multiple lines as well. Any thoughts? 

BTW, I could not find any function either in USGSCSM or in CSM itself reading a model state from disk. All I can see is a function for reading the ISD from disk, meaning loadImageSupportData(). And apparently a function for saving a state to disk is not present either.

**Comment by thareUSGS** [comment]
@oleg-alexandrov That is a good question. We should test that in GXP which also saves state as one giant string (within their image's "*.sup" supplementary file). I'm not sure GXP can handle multiple lines?

**Comment by jessemapel** [comment]
This is fairly straight forward to do and shouldn't conflict with the CSM API spec as it only requires the first line of the state string to be the the model name.

Reading and saving state to disk is not a part of the CSM API, that is the application's job.
