### ISSUE TITLE
Document how to share state between common SETs

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#368]
It would be very helpful for users to have documentation about how to pass model state between ISIS, ASP, and Socet-GXP

**Comment by oleg-alexandrov** [comment]
How ASP exports, imports, and transforms a model state is described here: https://stereopipeline.readthedocs.io/en/latest/examples.html#exporting-csm-model-state-after-bundle-adjustment-and-alignment

It may be desirable to have in this repo a standalone utility which can load a camera model in ISD format and save back its state, also load a model state file to verify that it is correct, and perhaps also do some sanity checks on it. Maybe the tool I am proposing here can do the job: https://github.com/USGS-Astrogeology/usgscsm/issues/359.

Then, somewhere within the ISIS repo or this repo there should exist a chapter on CSM where this and other aspects are documented. Note that ASP already has a doc, of which the above link is just a section.

**Comment by oleg-alexandrov** [comment]
The doc at https://github.com/USGS-Astrogeology/usgscsm/blob/dev/README.md describes the model state and the recently added tool in this lib which can manipulate it. Anything else needs to be done before this is closed?

**Comment by jessemapel** [comment]
@thareUSGS Does the README cover what you were looking for here?
