### ISSUE TITLE
Issue with loading the model from state

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/usgscsm#375]
The function:

 bool UsgsAstroPlugin::canModelBeConstructedFromState(const std::string &modelName, const std::string &modelState,
    csm::WarningList *warnings) const;

doesn't actually do anything with the input modelName. So, if told to load a SAR model via that variable, it will happily load whatever it can, even a Frame model. That is confusing. It is also different than the function canModelBeConstructedFromISD() which will take that model name input as well, but fails unless it gets what the name says.

One solution here is to omit that input model name, and the second is to check if the loaded model conforms to what the input asks for.

**Comment by jessemapel** [comment]
We can't remove the input model name as it's part of the API, even though I think it's the best solution. What we can do is add a check if the produced model has the correct name. That should be simple enough.

**Comment by oleg-alexandrov** [comment]
Closed in https://github.com/USGS-Astrogeology/usgscsm/pull/379.
