### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/usgscsm#376]
The link https://github.com/USGS-Astrogeology/pfeffernusse in the READMe file is broken.

**Comment by jessemapel** [comment]
hmm we had to pull that private for compliance reasons, I'm not sure what to do here besides just pull the link for now. @acpaquette @Kelvinrr thoughts?

**Comment by oleg-alexandrov** [comment]
Fixed in https://github.com/USGS-Astrogeology/usgscsm/pull/427.
