### ISSUE TITLE
triaxial and irregular body support

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/usgscsm#38]
Discuss triaxial issues and irregular body issues - who to handle within CSM API. For example, since the CSM implementation is up to user will the SET work if a irregular body might be used for I2G and G2I.

for more see: https://github.com/USGS-Astrogeology/CSM-CameraModel/wiki/CSM-and-triaxial

**Comment by jlaura** [comment]
This is a SET problem.
