### ISSUE TITLE
Administrative and Security Code Review

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#390]
All software must have an administrative security review before it is made publicly available by any method. This type of review ensures personal, private, or otherwise sensitive information is not included in the repository. Types of sensitive information include:

 -  Personally identifiable information (PII)
 -  Absolute file system paths
 -  Internal server host names or IP addresses
 -  Usernames/passwords

Administrative security reviews may be performed by any trusted person; the reviewer does not necessarily need a strong scientific or programming background. When migrating an existing project into any non-private Git repository, it is important to remember that the entire project history needs to be reviewed if that history is to be maintained after migration.

**Comment by scsides** [comment]
Admin review for USGSCSM:

There are no hostnames
There are no IP addresses
There are no username/passwords
There are no full paths
