### ISSUE TITLE
Update LineScan

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#41]
The LineScan Sensor model needs to be updated for the ISD specification updates.

- [ ] remove unused ISD keywords
- [ ] update the def
- [ ] update to use JSON

**Comment by jessemapel** [comment]
Currently, developing and testing this stuff requires working through the pytest framework. I'm going to put this off until we have cmake and ctest setup for this.

**Comment by jlaura** [comment]
Once #69 is merged, this should be good to go.
