### ISSUE TITLE
Systemic Errors in CTX (Line Scan Sensor) at the top (start or stop?) of images

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#423]
## Issue Description
CTX (line scan sensor model) is behaving strangely at the top of images.

## Examples
I am seeing consistent, systematic errors at the top of CTX images using the CSM. These errors are evident when using the sensor model to project from the image to the ground. In the attached images, the pink pluses (+) are a grid of points at every 1000 pixels in the image, projected to an BCBF coordinate. Note the extreme shift in the uppermost set of points in this first image (B05_011720_1832_XN_03N217W).
<img width="173" alt="Screen Shot 2022-09-11 at 6 13 13 AM" src="https://user-images.githubusercontent.com/2105468/189529518-70d097d5-4cc1-4c77-9711-384f21a1e491.png">

In the next image (B04_011377_1843_XN_04N212W), the effects are less pronounced at the top of the image. Instead, note how eight rows from the bottom, the regular grid suddenly widens. Points on the left (west) side of the image maintain good ground alignment while points on the right (east) side are incorrect.

<img width="157" alt="Screen Shot 2022-09-11 at 6 14 43 AM" src="https://user-images.githubusercontent.com/2105468/189529644-643729c0-6d74-4e66-918c-ea32dd9f63bd.png">

Finally, here is an example (B01_010018_1993_XN_19N191W) where the top rows of points are incorrect and are 'wrinkled' significantly to the top-right (NE). This is in contrast to the first example where the points shift dramatically to the left.

<img width="216" alt="Screen Shot 2022-09-11 at 6 18 56 AM" src="https://user-images.githubusercontent.com/2105468/189529765-569068b4-d013-4997-bf84-4bb19294071b.png">

## Processing Steps
- `spiceinit from=lvl0 shape=ellipsoid`
- `gen_csm` - to create the ISD file using the [gen_csm.py](https://stereopipeline.readthedocs.io/en/latest/examples.html#example-using-the-usgs-csm-linescan-sensor) script described by the ASP team.
- Knoten [generate_ground_point](https://github.com/USGS-Astrogeology/knoten/blob/master/knoten/csm.py#L118) using a high resolution DEM to compute the BCBF position of the intersection via the CSM. (I can provide the notebook and DEMs if desired).

## Environment
```
ale                       0.8.7           py310h91b1402_1    conda-forge
csm                       3.0.3.3              hc9558a2_0    conda-forge
cspice                    66                h7f98852_1015    conda-forge
isis                      6.0.0                         0    usgs-astrogeology
usgscsm                   1.6.0                h924138e_0    conda-forge
```
## Attachments
[ISDs.zip](https://github.com/USGS-Astrogeology/usgscsm/files/9542609/ISDs.zip)

**Comment by oleg-alexandrov** [comment]
Some simple sanity checks here (without using logic for generating ground points) could be:

 - Use cam2map on the .cub file. If things are so bad in the ISIS camera model as well, the result should be very distorted
 - Compare the ISIS and CSM image-to-ground and ground-to-image logic. There's an example here: https://stereopipeline.readthedocs.io/en/latest/tools/cam_test.html. This uses an ellipsoid rather than a DEM, but its height above the nominal Mars datum can be customized to agree with your DEM.

One could also try to do stereo with a well-behaved and poorly behaved CTX image, and inspect the DEM and error image (output of point2dem --errorimage), which would make use of results of triangulation, so projection from image to ground. 

Here of course talking about the tools I am familiar with. Maybe going directly to your knotten notebook may be faster.

On my side I've worked with LRO NAC CSM very exhaustively in the last month or so, on more than 800 images. There's some jitter, but no weirdness as you see. This would be interesting to track down.

**Comment by jlaura** [comment]
@oleg-alexandrov Thanks for the suggestions. I was having similar thoughts about how to isolate this yesterday afternoon.

The map projected images do not look warped as one would expect if the ephemeris information was not good. These were projected via the ISIS sensor though, so that really only validates the input SPICE.

Next, I did a sanity check on the ground to image logic into the DEM. The images below demonstrate that that is where the error is. This is simply calling the CSM, so this appears to be a knoten problem. The images below are the same three areas, with identical grid spacing. In this test, I set the height above the ellipsoid inside of the knoten generate_ground_point to zero. Therefore, the grids are projected onto the ellipsoid. Notice how the systematic errors completely disappear! Pending feedback, it seems that this issue needs to be migrated over to knoten.

#### Height above the ellipsoid 0
<p align="center">
<img width="194" alt="Screen Shot 2022-09-12 at 6 23 19 AM" src="https://user-images.githubusercontent.com/2105468/189665761-d4f409c9-34d9-49f4-8805-ef6b4946211e.png">
&nbsp;
<img width="168" alt="Screen Shot 2022-09-12 at 6 25 24 AM" src="https://user-images.githubusercontent.com/2105468/189666110-17df86a5-a5a8-4095-94f4-d2db61957aa1.png">
&nbsp;
<img width="201" alt="Screen Shot 2022-09-12 at 6 24 52 AM" src="https://user-images.githubusercontent.com/2105468/189666114-53034f57-bcd3-4ed3-b1fc-6a9b51437178.png">
</p>


#### Original images; Height above the ellipsoid from DEM.
<p align="center">
<img width="173" alt="Screen Shot 2022-09-11 at 6 13 13 AM" src="https://user-images.githubusercontent.com/2105468/189529518-70d097d5-4cc1-4c77-9711-384f21a1e491.png">
&nbsp;
<img width="216" alt="Screen Shot 2022-09-11 at 6 18 56 AM" src="https://user-images.githubusercontent.com/2105468/189529765-569068b4-d013-4997-bf84-4bb19294071b.png">
&nbsp;
<img width="157" alt="Screen Shot 2022-09-11 at 6 14 43 AM" src="https://user-images.githubusercontent.com/2105468/189529644-643729c0-6d74-4e66-918c-ea32dd9f63bd.png">
</p>

**Comment by jessemapel** [comment]
Yeah this looks like you are hitting the edge of a DEM pixel. I don't know if the knoten code is interpolating at all, but doing at least a bilinear interpolation on the DEM may fix this issue. I'm going to close this here as it doesn't appear to be a problem with the library or the model.
